name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t nextjs-app .

      - name: Push Docker image to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # SSH into the EC2 instance and deploy
          ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/app
            docker pull nextjs-app
            docker stop $(docker ps -q --filter "ancestor=nextjs-app")
            docker rm $(docker ps -aq --filter "ancestor=nextjs-app")
            docker run -d -p 3000:3000 nextjs-app
          EOF
